"""Shared constants for the orchestrator service."""

API_PREFIX = "/api/v1"
API_HEALTH_PATH = "/health"

DEFAULT_ENGINE_BASE_URL = "http://route-engine:8000"
DEFAULT_OSRM_BASE_URL = "http://osrm:5000"
DEFAULT_TIMEZONE = "Asia/Kolkata"
DEFAULT_DATABASE_URL = "mysql+pymysql://route:route@mysql:3306/route_engine"

ENV_DATABASE_URL = "DATABASE_URL"
ENV_ENGINE_BASE_URL = "ENGINE_BASE_URL"
ENV_OSRM_BASE_URL = "OSRM_BASE_URL"
ENV_ORCHESTRATOR_TZ = "ORCHESTRATOR_TZ"
ENV_ENGINE_TIMEOUT = "ENGINE_HTTP_TIMEOUT_SECONDS"
ENV_HEALTH_TIMEOUT = "HEALTH_HTTP_TIMEOUT_SECONDS"

DEFAULT_ENGINE_TIMEOUT_SECONDS = 60.0
DEFAULT_HEALTH_TIMEOUT_SECONDS = 3.0
